### ISSUE TITLE
"endless" nogis computation

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#112]
Steps to reproduce:

1. unzip [endless.zip](https://github.com/storm-fsv-cvut/smoderp2d/files/5760854/endless.zip) into `tests` directory
2. run
```
./bin/start-nogis-smoderp2d.py --config tests/endless/nogis.ini
```

@kavkapet @jerabekjak @pesekon2 Any idea why the computation takes so long time?

**Comment by pesekon2** [comment]
It is caused by soil parameters in `data_1D_soiltypes.csv`. I have tried to use a different soil type in the endless data (one copied from original test data) and the process have finished.

However, as I do not understand what exactly do those soil parameters mean, I cannot say why the process does not finish with them, as well as I cannot say if they make sense the way they are defined in your endless data, or not (although the computation length signs the latter).

**Comment by landam** [comment]
With slightly changed parameters [maxiter.zip](https://github.com/storm-fsv-cvut/smoderp2d/files/5761843/maxiter.zip) the computation fails with

```
./bin/start-nogis-smoderp2d.py --config tests/maxiter/nogis.ini
...
2021-01-03 17:08:54,512 - SMODERP2D - PROGRESS - 52 - [runoff:388]
2021-01-03 17:08:54,513 - SMODERP2D - CRITICAL - Maximum of iterations (max_iter = 40) was exceeded of at time [s]: 1800.3334999999995 - [exceptions:16]
Traceback (most recent call last):
  File "/home/martin/git/storm-fsv-cvut/smoderp2d/./bin/start-nogis-smoderp2d.py", line 15, in <module>
    start_smoderp2d()
  File "/home/martin/git/storm-fsv-cvut/smoderp2d/bin/start.py", line 11, in start_smoderp2d
    sys.exit(runner.run())
  File "/home/martin/git/storm-fsv-cvut/smoderp2d/bin/../smoderp2d/__init__.py", line 100, in run
    runoff.run()
  File "/home/martin/git/storm-fsv-cvut/smoderp2d/bin/../smoderp2d/runoff.py", line 329, in run
    raise MaxIterationExceeded(self.flow_control.max_iter,
smoderp2d.exceptions.MaxIterationExceeded: (40, 1800.3334999999995)
```

**Comment by jerabekjak** [comment]
The rounding has a reason here. The iteration loop compares two-time steps and do something if they are the same. The rounding in the just helps with the comparison...

**Comment by jerabekjak** [comment]
Well it the end the problem was the parameters. As we thought at the beginning (the husband is the first suspect...)

The `b` parameters **cannot be lower then 1**. And in the texting data the `b` is 0.52..... 
the parameter `y` can be 15 but usually it is lower. However the high 15 did not caused the error.....

**Comment by jerabekjak** [comment]
So it is a question whether we should keep the commit 268522f0131c8dd512adc6acb2e62d2f8c117272

**Comment by landam** [comment]
> Well it the end the problem was the parameters. As we thought at the beginning (the husband is the first suspect...)
> 
> The `b` parameters **cannot be lower then 1**. And in the texting data the `b` is 0.52.....
> the parameter `y` can be 15 but usually it is lower. However the high 15 did not caused the error.....

@jerabekjak @kavkapet Should be tested parameters range somehow? So for selected parameters to define min, max allowed values.

What is the "correct" value for `b`?

**Comment by landam** [comment]
> So it is a question whether we should keep the commit [268522f](https://github.com/storm-fsv-cvut/smoderp2d/commit/268522f0131c8dd512adc6acb2e62d2f8c117272)

Can this commit slowdown computation somehow, if not let's keep it.

**Comment by jerabekjak** [comment]
No, it should not increase the computation time.

**Comment by landam** [comment]
Wtih [maxiter.zip](https://github.com/storm-fsv-cvut/smoderp2d/files/5804476/maxiter.zip) computation finish.
